try:
    from .madara import MadaraSource, _Node, _TreeParser
except ImportError:
    pass

class MadaraSource:
    pass


class MhscansSource(MadaraSource):

    def get_preferences(self) -> list[SourcePreference]:
        # Autogenerated via heuristic port
        data = [
                {
                                "type": "checkbox",
                                "id": "pref_adult",
                                "name": "Show Adult Content",
                                "default": false
                }
]
        return [SourcePreference(**item) for item in data]

    def get_filters(self) -> list[SourceFilter]:
        # Autogenerated via heuristic port
        data = []
        return [SourceFilter(**item) for item in data]

    name = 'mhscans_es'
    display_name = 'MHScans'
    base_url = 'https://mhscans.com'
    language = 'es'
    manga_substring = 'series'
    load_more = 'always'
    use_new_chapter_endpoint = True
    chapter_url_suffix = '?style=list'
    supports_latest = True
    requests_per_minute = 60
    pages_profile = 'default'
    extra_headers = {}
    image_headers = {}


SOURCE = MhscansSource
