try:
    from .madara import (
        MadaraSource, _Node, _TreeParser
    )
except ImportError:
    pass

class MadaraSource:
    pass


class TemplescanespSource(MadaraSource):

    def get_preferences(self) -> list[SourcePreference]:
        # Autogenerated via heuristic port
        data = [
                {
                                "type": "checkbox",
                                "id": "pref_adult",
                                "name": "Show Adult Content",
                                "default": false
                }
]
        return [SourcePreference(**item) for item in data]

    def get_filters(self) -> list[SourceFilter]:
        # Autogenerated via heuristic port
        data = []
        return [SourceFilter(**item) for item in data]

    name = 'templescanesp_es'
    display_name = 'Temple Scan'
    base_url = 'https://aedexnox.akan01.com'
    language = 'es'
    manga_substring = 'serie'
    load_more = 'always'
    use_new_chapter_endpoint = False
    chapter_url_suffix = '?style=list'
    supports_latest = True
    requests_per_minute = 180
    pages_profile = 'redirect_form'
    extra_headers = {}
    image_headers = {}


SOURCE = TemplescanespSource
